yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment'
         ),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/',
         views.profile_follow,
         name='profile_follow'
         ),
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow,
         name='profile_unfollow'
         ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler403 = 'core.views.forbidden'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.internal_server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),

]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Заглавие',
        help_text='Напишите заглавие'
    )
    slug = models.SlugField(
        unique=True,
        max_length=20,
        db_index=True,
        default='title',
        verbose_name='Slug',
        help_text='Установите slug'
    )
    description = models.TextField(
        verbose_name='Описание',
        help_text='Напишите описание'
    )

    def __str__(self):
        return self.title


class Post(models.Model):
    pub_date = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        verbose_name='Дата публикации',
        help_text='Установите дату'
    )
    author = models.ForeignKey(
        User,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Автор',
        help_text='Выберите автора'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Выберите группу'
    )
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Введите текст поста'
    )
    image = models.ImageField(
        upload_to='posts/',
        blank=True,
        verbose_name='Картинка',
        help_text='Выберите фото'
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Запись',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор',
    )
    text = models.TextField(
        help_text='Введите текст комментария',
        verbose_name='Текст комментария',
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации',
    )

    class Meta:
        ordering = ['-created']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.post.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        related_name='follower',
        on_delete=models.CASCADE,
        verbose_name='Подписчик',
    )
    author = models.ForeignKey(
        User,
        related_name='following',
        on_delete=models.CASCADE,
        verbose_name='Автор записей',
    )

    class Meta:
        verbose_name = 'Подписчик'
        verbose_name_plural = 'Подписчики'
        constraints = [models.UniqueConstraint(
            fields=['user', 'author'],
            name='unique_follow')
        ]

    def __str__(self):
        return f'{self.user} --> {self.author}'

yatube/posts/forms.py
from django.forms import ModelForm

from .models import Post, Comment


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            'text': "Текст",
            'group': "Группа",
        }


class CommentForm(ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)
        help_texts = {
            'text': 'Введите текст комментария',
        }
        labels = {
            'text': 'Текст комментария',
        }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page
from django.views.decorators.csrf import csrf_exempt

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User
from .utils import get_page_context


@cache_page(20, key_prefix='index_page')
def index(request):
    post_list = Post.objects.all()
    context = {
        'page_obj': get_page_context(request, post_list),
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    context = {
        'group': group,
        'page_obj': get_page_context(request, post_list),
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = Post.objects.filter(author=author)
    following = Follow.objects.filter(
        user=request.user.id,
        author=author.id
    ).exists()
    context = {'page_obj': get_page_context(request, post_list),
               'author': author,
               'following': following,
               }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm()
    comments = post.comments.filter(post=post_id)
    context = {
        'post': post,
        'post_id': post_id,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
@csrf_exempt
def post_create(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        form.save()
        return redirect('posts:profile', request.user)
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post.pk, )
    form = PostForm(request.POST or None, instance=post)
    if form.is_valid():
        post.save()
        return redirect('posts:post_detail', post.pk, )
    is_edit = True
    context = {
        'form': form,
        'is_edit': is_edit
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    page_obj = get_page_context(request, post_list)
    template = 'posts/follow.html'
    content = {
        'page_obj': page_obj,
    }
    return render(request, template, content)


@login_required
def profile_follow(request, username):
    author_obj = get_object_or_404(User, username=username)
    user_obj = request.user
    follow_obj = Follow.objects.filter(
        user=user_obj,
        author=author_obj
    )
    if not follow_obj.exists() and author_obj != user_obj:
        Follow.objects.create(user=user_obj, author=author_obj)
    return redirect('posts:profile', username=author_obj.username)


@login_required
def profile_unfollow(request, username):
    author_obj = get_object_or_404(User, username=username)
    user_obj = request.user
    follow_obj = Follow.objects.filter(
        user=user_obj,
        author=author_obj
    )
    if follow_obj.exists():
        follow_obj.delete()
    return redirect('posts:profile', username=author_obj.username)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
{% if is_edit %}
Редактировать пост
{% else %}
Новый пост
{% endif %}
{% endblock %}
{% block content %}
<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-md-8 p-5">
            <div class="card">
                <div class="card-header">
                    {% if is_edit %}
                    Редактировать пост
                    {% else %}
                    Новый пост
                    {% endif %}
                </div>
                <div class="card-body">
                    {% load user_filters %}
                    {% if form.errors %}
                    {% for field in form %}
                    {% for error in field.errors %}
                    <div class="alert alert-danger">
                        {{ error|escape }}
                    </div>
                    {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        {{ error|escape }}
                    </div>
                    {% endfor %}
                    {% endif %}
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group row my-3 p-3">
                            <label form="{{ field.id_for_label }}">
                                {{ field.label }}
                                {% if field.field.required %}
                                <span class="required text-danger">*</span>
                                {% endif %}
                            </label>
                            {{ field|addclass:"form-control" }}
                            {% if field.help_text %}
                            <small
                                    id="{{ field.id_for_label }}-help"
                                    class="form-text text-muted"
                            >
                                {{ field.help_text|safe }}
                            </small>
                            {% endif %}
                        </div>
                        {% endfor %}
                        <div class="d-flex justify-content-end">
                            <button type="submit" class="btn btn-primary">
                                {% if is_edit %}
                                Сохранить
                                {% else %}
                                Добавить
                                {% endif %}
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% block title %}
Избранные записи
{% endblock %}
{% block content %}
<div class="container py-5">
{% include 'posts/includes/switcher.html' %}
<h1>Записи избранных авторов</h1>
{% for post in page_obj %}
{% include "posts/includes/post_card.html" %}
{% if not forloop.last %}
<hr>{% endif %}
{% endfor %}
{% include 'posts/includes/paginator.html' %}
{% endblock %}
</div>

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  {{ group.title }}
{% endblock %}
{% block content %}
<div class="container py-5">
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>
  {% for post in page_obj %}
    {% include "posts/includes/post_card.html" %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}
</div>

yatube/templates/posts/index.html
{% extends "base.html" %}
{% block title %}
  Последние обновления
{% endblock %}
{% block content %}
<div class="container py-5">
  {% include 'posts/includes/switcher.html' %}
  <h1>Последние обновления на сайте</h1>
  {% for post in page_obj %}
    {% include "posts/includes/post_card.html" %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}
</div>

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
Пост {{ post.text|truncatechars:30 }}
{% endblock %}
{% block content %}

<main>
    <div class="container py-5">
        <div class="row">
            <aside class="col-12 col-md-3">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        Дата публикации: {{ post.pub_date|date:"j E Y" }}
                    </li>
                    {% if post.group %}
                    <li class="list-group-item">
                        Группа: <a>{{ post.group.title }}</a>
                        <a href="{% url 'posts:group_posts' post.group.slug %}">
                            все записи группы
                        </a>
                        {% endif %}
                    </li>
                    <li class="list-group-item">
                        Автор: {{ post.author.get_full_name }}
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Всего постов автора: {{ post.author.posts.count }}
                    </li>
                    <li class="list-group-item">
                        <a href="{% url 'posts:profile' post.author.username %}">все
                            посты пользователя</a>
                        </a>
                    </li>
                </ul>
            </aside>
            <article class="col-12 col-md-9">

                {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                <img class="card-img my-2"
                     src="{{ im.url }}">
                {% endthumbnail %}
                <p>
                    {{ post.text }}
                </p>
                {% if post.author == request.user %}
                <a class="btn btn-primary"
                   href="{% url 'posts:post_edit' post.pk %}">
                    редактировать запись!
                </a>
                {% endif%}

                {% include "posts/includes/comments.html" %}
            </article>

        </div>
    </div>
</main>


{% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
Профиль пользователя {{ author.get_full_name }}
{% endblock %}
{% block content %}
<div class="container py-5">
    <div class="mb-5">
        <h1>Все посты пользователя {{ author }} </h1>
        <h3>Всего постов: {{ author.posts.count }} </h3>

        {% if request.user != author %}
        {% if following %}
        <a
                class="btn btn-lg btn-light"
                href="{% url 'posts:profile_unfollow' author.username %}"
                role="button"
        >
            Отписаться
        </a>
        {% else %}
        <a
                class="btn btn-lg btn-primary"
                href="{% url 'posts:profile_follow' author.username %}"
                role="button"
        >
            Подписаться
        </a>
        {% endif %}
        {% endif %}
    </div>


    {% for post in page_obj %}
    <article>
        <ul>
            <li>
                Автор: {{ author.username }}
                <a href="{% url 'posts:profile' post.author.username %}">все
                    посты пользователя</a>
            </li>
            <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
            {{ post.text }}
        </p>
        <a href="{% url 'posts:post_detail' post.pk %}">подробная
            информация </a>
        <br/>
        {% if post.group %}
        <a href="{% url 'posts:group_posts' post.group.slug %}">все записи
            группы</a>
        {% endif %}
        {% if not forloop.last %}
        <hr>
        {% endif %}
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
    </article>
</div>
{% endblock %}